version: "3.1"
name: "5-min-dariusz"
services:
  5-min-dariusz-db:
    container_name: "5-min-dariusz-db"
    image: postgres:16-alpine
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - 5-min-dariusz-db-data:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "5438:3001"
    env_file:
      - .env
    restart: unless-stopped
  frontend:
    build: ../i-need-dariusz-client
    ports:
      - "5437:80"
    depends_on:
      - backend

volumes:
  5-min-dariusz-db-data:
    driver: local
